/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emplist;

import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saksham
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        but_show_show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_show = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        but_SQL_emp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_add_sn = new javax.swing.JTextField();
        txt_add_name = new javax.swing.JTextField();
        txt_add_age = new javax.swing.JTextField();
        txt_add_sal = new javax.swing.JTextField();
        but_add_add = new javax.swing.JButton();
        but_add_reset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_edt_snw = new javax.swing.JTextField();
        txt_edt_namew = new javax.swing.JTextField();
        txt_edt_agew = new javax.swing.JTextField();
        txt_edt_salw = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_edt_snu = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txt_edt_nameu = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txt_edt_ageu = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txt_edt_salu = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        but_edt_edt = new javax.swing.JButton();
        but_edt_reset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_del_sn = new javax.swing.JTextField();
        txt_del_name = new javax.swing.JTextField();
        txt_del_age = new javax.swing.JTextField();
        txt_del_sal = new javax.swing.JTextField();
        but_del_del = new javax.swing.JButton();
        but_del_reset = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        but_show_show.setText("Show");
        but_show_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_show_showActionPerformed(evt);
            }
        });

        table_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_show);

        jLabel38.setText("Click on the button to create 'employee' table in test database in MySQL :");

        but_SQL_emp.setText("Employee");
        but_SQL_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_SQL_empActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_show_show)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(but_SQL_emp)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(but_SQL_emp))
                .addGap(24, 24, 24)
                .addComponent(but_show_show)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Show employee database", jPanel4);

        jLabel1.setText("Serial Number");

        jLabel2.setText("Name");

        jLabel3.setText("Age");

        jLabel4.setText("Salary");

        txt_add_sn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_add_snActionPerformed(evt);
            }
        });

        but_add_add.setText("Add");
        but_add_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_add_addActionPerformed(evt);
            }
        });

        but_add_reset.setText("Reset");
        but_add_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_add_resetActionPerformed(evt);
            }
        });

        jLabel9.setText(":");

        jLabel10.setText(":");

        jLabel11.setText(":");

        jLabel12.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(but_add_add)
                        .addGap(18, 18, 18)
                        .addComponent(but_add_reset))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_add_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_add_age, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_add_sn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(394, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_add_sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_add_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_add_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_add_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_add_add)
                    .addComponent(but_add_reset))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add employee database", jPanel1);

        jLabel20.setText("Where :");

        jLabel21.setText("Sr.No.");

        jLabel22.setText("Name");

        jLabel23.setText("Age");

        jLabel24.setText("Salary");

        jLabel25.setText(":");

        jLabel26.setText(":");

        jLabel27.setText(":");

        jLabel28.setText(":");

        txt_edt_snw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edt_snwActionPerformed(evt);
            }
        });

        jLabel29.setText("Sr.No.");

        jLabel30.setText(":");

        txt_edt_snu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edt_snuActionPerformed(evt);
            }
        });

        jLabel31.setText("Name");

        jLabel32.setText(":");

        jLabel33.setText("Age");

        jLabel34.setText(":");

        jLabel35.setText("Salary");

        jLabel36.setText(":");

        jLabel37.setText("Update :");

        but_edt_edt.setText("Edit");
        but_edt_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_edt_edtActionPerformed(evt);
            }
        });

        but_edt_reset.setText("Reset");
        but_edt_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_edt_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(txt_edt_snw, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_edt_agew, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_edt_namew, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_edt_salw, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(txt_edt_snu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel36)
                                            .addComponent(jLabel34))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_edt_ageu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_edt_nameu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_edt_salu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel37))
                        .addGap(93, 93, 93))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(but_edt_edt)
                        .addGap(18, 18, 18)
                        .addComponent(but_edt_reset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(txt_edt_snu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32)
                            .addComponent(txt_edt_nameu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel34)
                            .addComponent(txt_edt_ageu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36)
                            .addComponent(txt_edt_salu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel28)
                            .addComponent(txt_edt_snw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel27)
                            .addComponent(txt_edt_namew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(txt_edt_agew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(txt_edt_salw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_edt_edt)
                    .addComponent(but_edt_reset))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Employee database", jPanel2);

        jLabel5.setText("By Sr.No.");

        jLabel6.setText("By Name");

        jLabel7.setText("By Age");

        jLabel8.setText("By Salary");

        txt_del_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_del_nameActionPerformed(evt);
            }
        });

        but_del_del.setText("Delete");
        but_del_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_del_delActionPerformed(evt);
            }
        });

        but_del_reset.setText("Reset");
        but_del_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_del_resetActionPerformed(evt);
            }
        });

        jLabel14.setText(":");

        jLabel15.setText(":");

        jLabel16.setText(":");

        jLabel17.setText(":");

        jLabel18.setText("Enter any one of the following fields and click on delete :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addComponent(jLabel16))
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_del_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_del_age, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_del_sn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_del_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(but_del_del)
                        .addGap(18, 18, 18)
                        .addComponent(but_del_reset))
                    .addComponent(jLabel18))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_del_sn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_del_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_del_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_del_sal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(but_del_reset)
                    .addComponent(but_del_del))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete employee database", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_add_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_add_addActionPerformed
        try {
            int sn,age,sal;
            String name;
            sn=Integer.parseInt(txt_add_sn.getText());
            name=txt_add_name.getText();
            age=Integer.parseInt(txt_add_age.getText());
            sal=Integer.parseInt(txt_add_sal.getText());
//            Statement emp;
            PreparedStatement prstat;
            Connection con;
            con=DriverManager.getConnection("jdbc:mysql://localhost/test");
            //System.out.println("connection is ok");
//            emp=con.createStatement();
            prstat=con.prepareStatement("insert into employee values(?,?,?,?)");
            prstat.setInt(1, Integer.parseInt(txt_add_sn.getText()));
            prstat.setString(2, txt_add_name.getText());
            prstat.setInt(3, Integer.parseInt(txt_add_age.getText()));
            prstat.setInt(4, Integer.parseInt(txt_add_sal.getText()));
            prstat.execute();
//            emp.executeUpdate("insert into employee values(" + String.valueOf(sn) + ",'" + name + "'," + String.valueOf(age) + "," + String.valueOf(sal) + ")");
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_add_age.setText("");
        txt_add_name.setText("");
        txt_add_sal.setText("");
        txt_add_sn.setText("");
        JOptionPane.showMessageDialog(this, "Successfully added");
    }//GEN-LAST:event_but_add_addActionPerformed

    private void txt_del_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_del_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_del_nameActionPerformed

    private void but_add_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_add_resetActionPerformed
        txt_add_age.setText("");
        txt_add_name.setText("");
        txt_add_sal.setText("");
        txt_add_sn.setText("");
    }//GEN-LAST:event_but_add_resetActionPerformed

    private void txt_add_snActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_add_snActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_add_snActionPerformed

    private void but_del_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_del_delActionPerformed
        try {
            int sn=-1,age=-1,sal=-1;
            String name="";
            Statement emp;
            Connection con;
            con=DriverManager.getConnection("jdbc:mysql://localhost/test");
            emp=con.createStatement();
            try
            {
                sn=Integer.parseInt(txt_del_sn.getText());
            }
            catch(Exception ex)
            {
                
            }
            try
            {
                name=txt_del_name.getText();
            }
            catch(Exception ex)
            {
                
            }
            try
            {
                age=Integer.parseInt(txt_del_age.getText());
            }
            catch(Exception ex)
            {
                
            }
            try
            {
                sal=Integer.parseInt(txt_del_sal.getText());
            }
            catch(Exception ex)
            {
                
            }
            
            if(sn != -1)
            {
                sn=Integer.parseInt(txt_del_sn.getText());
                emp.executeUpdate("delete from employee where SrNum=" + String.valueOf(sn));
            }
            
            
            if(name!="")
            {
                name=txt_del_name.getText();
                emp.executeUpdate("delete from employee where Name='" + name + "'");
            }
            if(age != -1)
            {
                age=Integer.parseInt(txt_del_age.getText());
                emp.executeUpdate("delete from employee where Age=" + String.valueOf(age));
            }
            if(sal != -1)
            {
                sal=Integer.parseInt(txt_del_sal.getText());
                emp.executeUpdate("delete from employee where Salary=" + String.valueOf(sal));
            }
            
            
            
//            if(sn==-1 && name=="" && age == -1 && sal == -1)
//            {
//                JOptionPane.showMessageDialog(this, "Enter a field");
//            }
            
            
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_del_age.setText("");
        txt_del_name.setText("");
        txt_del_sal.setText("");
        txt_del_sn.setText("");
        JOptionPane.showMessageDialog(this, "Successfully deleted");
    }//GEN-LAST:event_but_del_delActionPerformed

    private void but_del_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_del_resetActionPerformed
        txt_del_age.setText("");
        txt_del_name.setText("");
        txt_del_sal.setText("");
        txt_del_sn.setText("");
    }//GEN-LAST:event_but_del_resetActionPerformed

    
    
    
    private void but_show_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_show_showActionPerformed
        try {
            Connection con;
            ResultSet rs;
            Statement stat;
            con=DriverManager.getConnection("jdbc:mysql://localhost/test");
            stat=con.createStatement();            
            rs=stat.executeQuery("select * from employee");       
          //  txt_show_tab.setText("Sr.No." + "\tName" + "\t\tAge" + "\tSalary\n");
            
            try
            {
            
                Vector<String> v;
                DefaultTableModel tm=new DefaultTableModel();
                
                Vector<String> v1=new Vector<>();
                v1.add("Sr.No.");
                v1.add("Name");
                v1.add("Age");
                v1.add("Salary");
                tm=new DefaultTableModel(v1, 0);
                //tm.setColumnCount(4);

            //rs.next();
            while(rs.next())
            {    
    //            v.clear();
                v = new Vector<String>();
                v.add(String.valueOf(rs.getInt("SrNum")));
                v.add(rs.getString("Name"));
                v.add(String.valueOf(rs.getInt("Age")));
                v.add(String.valueOf(rs.getInt("Salary")));
                tm.addRow(v);
            }
            table_show.setModel(tm);
            //table_show.getColumnModel().getColumn(0).setPreferredWidth(10);
                
            
//                rs.next();
//            while(rs.next())
  //          {    
                
    //            v.clear();
//                v.add(String.valueOf(rs.getInt("SrNum")));
//                v.add(rs.getString("Name"));
//                v.add(String.valueOf(rs.getInt("Age")));
//                v.add(String.valueOf(rs.getInt("Salary")));
//                tm.addRow(v);
//    //      
                
            
            
                
            
            }
            catch(Exception ex)
            {System.out.println(ex);}
            
            
//            while(rs.next())
//            {
//                rs.getInt("SrNum");
//                txt_show_tab.setText(txt_show_tab.getText() + String.valueOf(rs.getInt("SrNum")));
//                rs.getString("Name");
//                txt_show_tab.setText(txt_show_tab.getText() + "\t" + rs.getString("Name"));
//                rs.getInt("Age");
//                txt_show_tab.setText(txt_show_tab.getText() + "\t\t" + String.valueOf(rs.getInt("Age")));
//                rs.getInt("Salary");
//                txt_show_tab.setText(txt_show_tab.getText() + "\t" + String.valueOf(rs.getInt("Salary")) + "\n");
//            }
            
//            DefaultTableModel tm = null;
//            tm.setValueAt("hello", 1, 1);
//            tm.setColumnCount(4);
//            while(rs.next())
//            {
//                rs.getInt("SrNum");
//                tm.addRow(Object[].class 1);
//            }
     
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_but_show_showActionPerformed

    private void txt_edt_snwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edt_snwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edt_snwActionPerformed

    private void txt_edt_snuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edt_snuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edt_snuActionPerformed

    private void but_edt_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_edt_edtActionPerformed
        
        try
        {
          
            int snw=-1,agew=-1,salw=-1;
            String namew="";
            int snu=-1,ageu=-1,salu=-1;
            String nameu="";
            
            String str1="";
            String str2="";
            
            Statement emp;
            Connection con;
            con=DriverManager.getConnection("jdbc:mysql://localhost/test");
            emp=con.createStatement();
            try
            {
                snw=Integer.parseInt(txt_edt_snw.getText());
            }
            catch(Exception ex)
            {
               
            }
            try
            {
                namew=txt_edt_namew.getText();
            }
            catch(Exception ex)
            {
               
            }
            try
            {
                agew=Integer.parseInt(txt_edt_agew.getText());
            }
            catch(Exception ex)
            {
                
            }
            try
            {
                salw=Integer.parseInt(txt_edt_salw.getText());
            }
            catch(Exception ex)
            {
                    
            }
            
            
            
            if(snw != -1)
            {
                str1="SrNum="+String.valueOf(snw);
            }
            else if(agew != -1)
            {
                str1="Age="+String.valueOf(agew);
            }
            else if(salw != -1)
            {
                str1="Salary="+String.valueOf(salw);
            }
            else if(namew != "")
            {
                str1="Name='"+namew + "'";
            }
            else
            {
                
            }
            //System.out.println(str1);
            
            try
            {
                snu=Integer.parseInt(txt_edt_snu.getText());
            }
            catch(Exception ex)
            {
               
            }
            try
            {
                nameu=txt_edt_nameu.getText();
            }
            catch(Exception ex)
            {
               
            }
            try
            {
                ageu=Integer.parseInt(txt_edt_ageu.getText());
            }
            catch(Exception ex)
            {
                
            }
            try
            {
                salu=Integer.parseInt(txt_edt_salu.getText());
            }
            catch(Exception ex)
            {
                    
            }
            
             
            if(snu != -1)
            {
                str2="SrNum="+String.valueOf(snu);
            }
            else if(ageu != -1)
            {
                str2="Age="+String.valueOf(ageu);
            }
            else if(salu != -1)
            {
                str2="Salary="+String.valueOf(salu);
            }
            else if(nameu != "")
            {
                str2="Name='"+nameu + "'";
            }
            else
            {
                
            }
            
            
            
            emp.executeUpdate("update employee set " + str2 + " where " + str1);
            
            txt_edt_snw.setText("");
            txt_edt_namew.setText("");
            txt_edt_agew.setText("");
            txt_edt_salw.setText("");
            txt_edt_snu.setText("");
            txt_edt_nameu.setText("");
            txt_edt_ageu.setText("");
            txt_edt_salu.setText("");
            JOptionPane.showMessageDialog(this, "Successfully edited");
            
        }
        catch(SQLException ex)
        {
        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
              
        }
               
        
        
    }//GEN-LAST:event_but_edt_edtActionPerformed

    private void but_edt_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_edt_resetActionPerformed
        txt_edt_snw.setText("");
        txt_edt_namew.setText("");
        txt_edt_agew.setText("");
        txt_edt_salw.setText("");
        txt_edt_snu.setText("");
        txt_edt_nameu.setText("");
        txt_edt_ageu.setText("");
        txt_edt_salu.setText("");
            
    }//GEN-LAST:event_but_edt_resetActionPerformed

    private void but_SQL_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_SQL_empActionPerformed
        try {
            Statement stat;
            Connection con;
            con=DriverManager.getConnection("jdbc:mysql://localhost/test");
            stat=con.createStatement();
            stat.executeUpdate("create table employee(SrNum INT(255),Name VARCHAR(100),Age INT(255),Salary INT(255));");
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JOptionPane.showMessageDialog(this, "Successfully created");
    }//GEN-LAST:event_but_SQL_empActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton but_SQL_emp;
    private javax.swing.JButton but_add_add;
    private javax.swing.JButton but_add_reset;
    private javax.swing.JButton but_del_del;
    private javax.swing.JButton but_del_reset;
    private javax.swing.JButton but_edt_edt;
    private javax.swing.JButton but_edt_reset;
    private javax.swing.JButton but_show_show;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable table_show;
    private javax.swing.JTextField txt_add_age;
    private javax.swing.JTextField txt_add_name;
    private javax.swing.JTextField txt_add_sal;
    private javax.swing.JTextField txt_add_sn;
    private javax.swing.JTextField txt_del_age;
    private javax.swing.JTextField txt_del_name;
    private javax.swing.JTextField txt_del_sal;
    private javax.swing.JTextField txt_del_sn;
    private javax.swing.JTextField txt_edt_ageu;
    private javax.swing.JTextField txt_edt_agew;
    private javax.swing.JTextField txt_edt_nameu;
    private javax.swing.JTextField txt_edt_namew;
    private javax.swing.JTextField txt_edt_salu;
    private javax.swing.JTextField txt_edt_salw;
    private javax.swing.JTextField txt_edt_snu;
    private javax.swing.JTextField txt_edt_snw;
    // End of variables declaration//GEN-END:variables
}
